/* Browser port of src/main/java/com/schedule - Java remains authoritative. */
const CONFIG = {
  GUESTS_PER_WORKER: 10,
  FIRST_SET_A_EXCEPTION_GUEST_LIMIT: 10,
  MAIN_ZONE_LAST_ROOM: 4,
  A_LEAD_MINUTES: 30,
  B_TRAIL_MINUTES: 45,
  B_OVERLAP_TOLERANCE_MINUTES: 30,
  C_PROXIMITY_MINUTES: 15,
  LEAD_WEIGHT_FACTOR: 100,
  ZONE_MATCH_BONUS: 80,
  ZONE_MISMATCH_PENALTY: 80,
  PREFERRED_PAIR_BONUS: 60,
  SAME_FAMILY_BONUS: 30,
  CROSS_FAMILY_PENALTY: 50,
  A_OVERLAP_PENALTY: 40,
  B_OVERLAP_PENALTY: 8,
  C_PROXIMITY_PENALTY: 12,
  WORKLOAD_PENALTY: 5,
  TRANSITION_PENALTY: 15,
  LEAD_LOAD_PENALTY: 25,
  DEFAULT_THEATER: "default"
};
function workersRequired(g){if(g<=0)return 0;return Math.floor((g+CONFIG.GUESTS_PER_WORKER-1)/CONFIG.GUESTS_PER_WORKER)}
function parseHm(v){const m=/^(\d{1,2}):(\d{2})$/.exec(String(v||"").trim());if(!m)return null;const h=+m[1],n=+m[2];if(h<0||h>23||n<0||n>59)return null;return h*60+n}
function formatHm(m){const w=((m%(24*60))+24*60)%(24*60);return String(Math.floor(w/60)).padStart(2,"0")+":"+String(w%60).padStart(2,"0")}
function rangeLabel(r){return r?formatHm(r.start)+" - "+formatHm(r.end):""}
function overlaps(a,b){return a.start<b.end&&b.start<a.end}
function containsRange(w,r){return r.start>=w.start&&r.end<=w.end}
function overlapMinutes(a,b){return overlaps(a,b)?Math.min(a.end,b.end)-Math.max(a.start,b.start):0}
function zoneOfRoom(r){return Number(r)<=CONFIG.MAIN_ZONE_LAST_ROOM?"MAIN":"SIDE"}
function sameFamily(a,b){return zoneOfRoom(a)===zoneOfRoom(b)}
function preferredPair(l,r){const a=Math.min(+l,+r),b=Math.max(+l,+r);return (a===1&&(b===2||b===3))||(a===2&&b===4)||(a===5&&b===6)||(a===6&&b===7)}
function deriveWindows(startHm,dur){const start=parseHm(startHm),d=+dur;if(start==null||!d||start<CONFIG.A_LEAD_MINUTES)return null;const cEnd=start+d;if(cEnd>24*60)return null;return{start,duration:d,aWindow:{start:start-CONFIG.A_LEAD_MINUTES,end:start},bWindow:{start:cEnd-CONFIG.B_TRAIL_MINUTES,end:cEnd},cEnd,operationalSpan:{start:start-CONFIG.A_LEAD_MINUTES,end:cEnd}}}
function showtimesOf(show){return Array.isArray(show.showtimes)?show.showtimes:[]}
function flattenShowtimes(shows){const items=[];for(const show of shows){for(const showtime of showtimesOf(show)){const windows=deriveWindows(showtime.start,showtime.duration);if(!windows)continue;items.push({show,showtime,windows,guests:+show.guests||0})}}items.sort((a,b)=>a.windows.start-b.windows.start||String(a.show.id).localeCompare(String(b.show.id))||String(a.showtime.id).localeCompare(String(b.showtime.id)));return items}
function buildFirstSetCohort(items){if(!items.length)return new Set();const earliest=Math.min(...items.map(i=>i.windows.start));const cohort=new Set(items.filter(i=>i.windows.start===earliest).map(i=>i.showtime.id));let expanded=true;while(expanded){expanded=false;for(const c of items){if(cohort.has(c.showtime.id))continue;for(const m of items){if(!cohort.has(m.showtime.id))continue;if(overlaps(c.windows.aWindow,m.windows.aWindow)){cohort.add(c.showtime.id);expanded=true;break}}}}return cohort}
function isAvailable(worker,span){const wins=(worker.availability||[]).map(w=>({start:parseHm(w.start),end:parseHm(w.end)})).filter(r=>r.start!=null&&r.end!=null&&r.start<r.end);if(!wins.length)return true;return wins.some(w=>containsRange(w,span))}
function leadWeight(worker,theater){const key=theater||CONFIG.DEFAULT_THEATER;if(worker.leadWeightByTheater&&worker.leadWeightByTheater[key]!=null)return +worker.leadWeightByTheater[key];if(worker.leadWeight!=null&&worker.leadWeight!=="")return +worker.leadWeight;return 5}
function firstSetExceptionApplies(existing,candidate,cohort){if(!cohort.has(existing.showtimeId)||!cohort.has(candidate.showtime.id))return false;return existing.guests<CONFIG.FIRST_SET_A_EXCEPTION_GUEST_LIMIT&&candidate.guests<CONFIG.FIRST_SET_A_EXCEPTION_GUEST_LIMIT}
function strictlyInside(range,t){return t>range.start&&t<range.end}
function aOverlapsC(ex,w){return strictlyInside(ex.aWindow,w.cEnd)||strictlyInside(w.aWindow,ex.cEnd)}
function hasOrdinaryAConflict(ex,cand,cohort){if(overlaps(ex.aWindow,cand.windows.aWindow))return !firstSetExceptionApplies(ex,cand,cohort);if(overlaps(ex.aWindow,cand.windows.bWindow)||overlaps(ex.bWindow,cand.windows.aWindow))return true;return aOverlapsC(ex,cand.windows)}
function eligible(worker,cand,asg,cohort){if(!isAvailable(worker,cand.windows.operationalSpan))return false;for(const ex of asg){if(ex.workerId!==worker.id)continue;if(ex.showId===cand.show.id&&ex.showtimeId===cand.showtime.id)return false;if(hasOrdinaryAConflict(ex,cand,cohort))return false;if(overlapMinutes(ex.bWindow,cand.windows.bWindow)>CONFIG.B_OVERLAP_TOLERANCE_MINUTES)return false}return true}
function establishedZone(worker,asg){let z=null;for(const a of asg){if(a.workerId!==worker.id)continue;if(!z)z=a.zone;else if(z!==a.zone)return null}return z||worker.preferredZone||null}
function zoneAffinity(worker,asg,zone){const ref=establishedZone(worker,asg)||worker.preferredZone||null;if(!ref)return 0;return ref===zone?CONFIG.ZONE_MATCH_BONUS:-CONFIG.ZONE_MISMATCH_PENALTY}
function familyAffinity(a,b){if(preferredPair(a,b))return CONFIG.PREFERRED_PAIR_BONUS;if(sameFamily(a,b))return CONFIG.SAME_FAMILY_BONUS;return -CONFIG.CROSS_FAMILY_PENALTY}
function proximityPenalty(m){if(!m||m>CONFIG.C_PROXIMITY_MINUTES)return 0;return (CONFIG.C_PROXIMITY_MINUTES-m+1)*CONFIG.C_PROXIMITY_PENALTY}
function scoreWorker(worker,cand,asg){const zone=zoneOfRoom(cand.showtime.room);let family=0,aO=0,bO=0,cMin=Infinity,n=0,leads=0,last=null;for(const ex of asg){if(ex.workerId!==worker.id)continue;n++;if(ex.lead)leads++;last=ex;if(overlaps(ex.aWindow,cand.windows.aWindow)){aO+=overlapMinutes(ex.aWindow,cand.windows.aWindow);family+=familyAffinity(ex.roomNumber,cand.showtime.room)}bO+=overlapMinutes(ex.bWindow,cand.windows.bWindow);const d=Math.abs(ex.cEnd-cand.windows.cEnd);if(d<cMin)cMin=d}if(cMin===Infinity)cMin=0;const tr=last&&last.zone!==zone?1:0;const coverageScore=zoneAffinity(worker,asg,zone)+family-aO*CONFIG.A_OVERLAP_PENALTY-bO*CONFIG.B_OVERLAP_PENALTY-proximityPenalty(cMin)-n*CONFIG.WORKLOAD_PENALTY-tr*CONFIG.TRANSITION_PENALTY;const leadScore=leadWeight(worker,cand.show.theater)*CONFIG.LEAD_WEIGHT_FACTOR+zoneAffinity(worker,asg,zone)-leads*CONFIG.LEAD_LOAD_PENALTY-aO*2-bO-proximityPenalty(cMin)-tr*CONFIG.TRANSITION_PENALTY;return{coverageScore,leadScore}}
function createAssignment(worker,cand,slot,score){return{workerId:worker.id,showId:cand.show.id,showtimeId:cand.showtime.id,roomNumber:+cand.showtime.room,zone:zoneOfRoom(cand.showtime.room),guests:cand.guests,aWindow:cand.windows.aWindow,bWindow:cand.windows.bWindow,cEnd:cand.windows.cEnd,start:cand.windows.start,coverageSlot:slot,lead:false,score,warnings:[]}}
function warn(code,workerId,exId,newId,mins,exc,message){return{code,workerId,existingShowtimeId:exId,newShowtimeId:newId,existingAssignmentId:exId||"",newAssignmentId:newId,overlapMinutes:mins,exceptionApplied:!!exc,message}}
function evaluateDiagnostics(worker,cand,created,prior,all,cohort,workers){const out=[];const mine=prior.filter(a=>a.workerId===worker.id);for(const ex of mine){const aO=overlapMinutes(ex.aWindow,cand.windows.aWindow);if(aO>0){const exc=firstSetExceptionApplies(ex,cand,cohort);out.push(warn("A_OVERLAP",worker.id,ex.showtimeId,cand.showtime.id,aO,exc,exc?"First-set A overlap permitted because each room is under "+CONFIG.FIRST_SET_A_EXCEPTION_GUEST_LIMIT+" guests":"A windows overlap"));out.push(warn("DOUBLE_A",worker.id,ex.showtimeId,cand.showtime.id,aO,exc,preferredPair(ex.roomNumber,cand.showtime.room)?"Double-A on preferred pair "+ex.roomNumber+" <-> "+cand.showtime.room:sameFamily(ex.roomNumber,cand.showtime.room)?"Double-A inside the same room family":"Double-A across room families "+ex.roomNumber+" <-> "+cand.showtime.room));if(exc)out.push(warn("FIRST_SET_A_EXCEPTION",worker.id,ex.showtimeId,cand.showtime.id,aO,true,"First-set-of-day A exception used"))}const bO=overlapMinutes(ex.bWindow,cand.windows.bWindow);if(bO>0)out.push(warn("B_OVERLAP",worker.id,ex.showtimeId,cand.showtime.id,bO,false,bO>CONFIG.B_OVERLAP_TOLERANCE_MINUTES?"B overlap exceeds the "+CONFIG.B_OVERLAP_TOLERANCE_MINUTES+"-minute tolerance":"B windows overlap"));const cD=Math.abs(ex.cEnd-cand.windows.cEnd);if(cD<=CONFIG.C_PROXIMITY_MINUTES)out.push(warn("C_PROXIMITY",worker.id,ex.showtimeId,cand.showtime.id,cD,false,cD===0?"C end events coincide":"C end events are within "+CONFIG.C_PROXIMITY_MINUTES+" minutes"));if(ex.zone!==created.zone)out.push(warn("ZONE_SWITCH",worker.id,ex.showtimeId,cand.showtime.id,0,false,"Worker moves between "+ex.zone+" and "+created.zone));if(!sameFamily(ex.roomNumber,created.roomNumber)&&aO>0)out.push(warn("ROOM_FAMILY_SWITCH",worker.id,ex.showtimeId,cand.showtime.id,aO,false,"Overlapping A covers different room families ("+ex.roomNumber+" and "+created.roomNumber+")"))}if(mine.length+1>=4)out.push(warn("WORKLOAD",worker.id,null,cand.showtime.id,mine.length+1,false,"Worker already carries "+(mine.length+1)+" showtimes"));if(created.lead){const w=leadWeight(worker,cand.show.theater);const best=all.filter(a=>a.showId===cand.show.id&&a.showtimeId===cand.showtime.id).reduce((m,a)=>{const p=workers.find(x=>x.id===a.workerId);return Math.max(m,p?leadWeight(p,cand.show.theater):0)},w);if(w<=3||w+2<=best)out.push(warn("LEAD_QUALITY",worker.id,null,cand.showtime.id,w,false,"Lead weight "+w+"/10 for "+(cand.show.theater||CONFIG.DEFAULT_THEATER)))}return out}
function arbitrateLead(anchored,asg,workers){const on=asg.filter(a=>a.showId===anchored.show.id&&a.showtimeId===anchored.showtime.id);if(!on.length)return;on.forEach(a=>a.lead=false);let best=null,bestScore=-Infinity;for(const a of on){const w=workers.find(x=>x.id===a.workerId);if(!w)continue;const s=scoreWorker(w,anchored,asg).leadScore;if(s>bestScore||(s===bestScore&&w.id<(best?best.workerId:""))){best=a;bestScore=s}}if(best)best.lead=true}
function solve(workers,shows){const items=flattenShowtimes(shows);const cohort=buildFirstSetCohort(items);const assignments=[];for(const cand of items){const required=workersRequired(cand.guests);const used=new Set();for(let slot=0;slot<required;slot++){let best=null,bestScore=-Infinity;for(const w of workers){if(used.has(w.id)||!eligible(w,cand,assignments,cohort))continue;const s=scoreWorker(w,cand,assignments).coverageScore;if(best==null||s>bestScore||(s===bestScore&&w.id<best.id)){best=w;bestScore=s}}if(!best)continue;assignments.push(createAssignment(best,cand,slot,bestScore));used.add(best.id)}arbitrateLead(cand,assignments,workers)}const chrono=assignments.slice().sort((a,b)=>a.aWindow.start-b.aWindow.start||String(a.showtimeId).localeCompare(String(b.showtimeId))||String(a.workerId).localeCompare(String(b.workerId)));const warnings=[];const seen=[];for(const a of chrono){const w=workers.find(x=>x.id===a.workerId);const c=items.find(i=>i.show.id===a.showId&&i.showtime.id===a.showtimeId);if(w&&c){a.warnings=evaluateDiagnostics(w,c,a,seen,assignments,cohort,workers);warnings.push(...a.warnings)}seen.push(a)}const gaps=[];for(const show of shows){const req=workersRequired(show.guests);for(const st of showtimesOf(show)){const assigned=new Set(assignments.filter(s=>s.showId===show.id&&s.showtimeId===st.id).map(s=>s.workerId)).size;if(assigned<req)gaps.push({showId:show.id,showtimeId:st.id,setTimeId:st.id,required:req,assigned,missing:req-assigned})}}return{assignments,coverageGaps:gaps,warnings,assignmentCount:assignments.length,gapCount:gaps.reduce((s,g)=>s+g.missing,0),fullyCovered:gaps.length===0,firstSetCohort:[...cohort]}}
function slotRange(s){return s.aWindow||s.bWindow||null}
function slotType(){return "ST"}
function generateDaySheet(dayLabel,workers,shows,result){const wb=Object.fromEntries(workers.map(w=>[w.id,w]));const sb=Object.fromEntries(shows.map(s=>[s.id,s]));const L=["============================================================","SHOWFLOW MASTER DAY SHEET","============================================================","DAY: "+dayLabel,"","SYSTEM SUMMARY","------------------------------------------------------------","Guests per worker target: "+CONFIG.GUESTS_PER_WORKER,"Assignments: "+result.assignmentCount,"Coverage gaps: "+result.gapCount,"Warnings: "+result.warnings.length,"Fully covered: "+result.fullyCovered,"","SHOW COVERAGE","------------------------------------------------------------"];for(const show of shows){const req=workersRequired(show.guests);L.push(show.name+" ["+show.id+"] - "+show.guests+" guests, "+req+" workers per showtime");for(const st of showtimesOf(show)){const assigned=new Set(result.assignments.filter(s=>s.showId===show.id&&s.showtimeId===st.id).map(s=>s.workerId)).size;const w=deriveWindows(st.start,st.duration);const d=w?"A "+rangeLabel(w.aWindow)+"  B "+rangeLabel(w.bWindow)+"  C "+formatHm(w.cEnd):"";L.push("  room "+st.room+"  "+st.start+" +"+st.duration+"m  "+d+" -> "+assigned+"/"+req)}L.push("")}L.push("MASTER ASSIGNMENT SCHEDULE","------------------------------------------------------------");result.assignments.slice().sort((a,b)=>a.aWindow.start-b.aWindow.start||String(a.showId).localeCompare(String(b.showId))).forEach(s=>{const wn=wb[s.workerId]?wb[s.workerId].name:s.workerId;const sn=sb[s.showId]?sb[s.showId].name:s.showId;L.push(String(wn).padEnd(12)+String(sn).padEnd(20)+("rm"+s.roomNumber).padEnd(5)+formatHm(s.start).padEnd(6)+("C="+formatHm(s.cEnd)).padEnd(9)+"slot="+s.coverageSlot+(s.lead?" LEAD":"")+(s.warnings.length?" [WARNINGS]":""))});L.push("","COVERAGE GAPS","------------------------------------------------------------");if(!result.coverageGaps.length)L.push("NONE");else for(const g of result.coverageGaps)L.push((sb[g.showId]?sb[g.showId].name:g.showId)+" / "+(g.showtimeId||g.setTimeId)+": missing "+g.missing+" worker(s)");L.push("","WARNINGS","------------------------------------------------------------");if(!result.warnings.length)L.push("NONE");else for(const w of result.warnings)L.push("- WARNING: "+w.message+(w.overlapMinutes?" ("+w.overlapMinutes+" min)":""));L.push("","============================================================","END MASTER DAY SHEET","============================================================");return L.join("\n")}
function generateWorkerSheet(worker,shows,result){const sb=Object.fromEntries(shows.map(s=>[s.id,s]));const asg=result.assignments.filter(s=>s.workerId===worker.id).slice().sort((a,b)=>a.aWindow.start-b.aWindow.start);const L=["============================================================","SHOWFLOW WORKER SCHEDULE","============================================================","WORKER: "+worker.name+" ["+worker.id+"]","","ASSIGNMENTS","------------------------------------------------------------"];if(!asg.length)L.push("NONE");else for(const s of asg){L.push("- "+(sb[s.showId]?sb[s.showId].name:s.showId)+" / room "+s.roomNumber+" / "+s.showtimeId+" / start "+formatHm(s.start)+" / C "+formatHm(s.cEnd)+(s.lead?" / LEAD":""));for(const w of s.warnings)L.push("    WARNING: "+w.message+(w.overlapMinutes?" ("+w.overlapMinutes+" min)":""))}L.push("","TOTAL ASSIGNMENTS: "+asg.length,"","OVERLAP WARNINGS","------------------------------------------------------------");const ww=result.warnings.filter(w=>w.workerId===worker.id);if(!ww.length)L.push("NONE");else for(const w of ww)L.push("- WARNING: "+w.message+(w.overlapMinutes?" ("+w.overlapMinutes+" min)":""));L.push("","============================================================","END WORKER SCHEDULE","============================================================");return L.join("\n")}
function sampleDay(){return{dayLabel:"Saturday Floor",workers:[{id:"w1",name:"Ava",preferredZone:"MAIN",leadWeight:9,availability:[{start:"10:00",end:"22:00"}]},{id:"w2",name:"Ben",preferredZone:"MAIN",leadWeight:7,availability:[{start:"12:00",end:"23:00"}]},{id:"w3",name:"Cara",preferredZone:"SIDE",leadWeight:8,availability:[{start:"10:00",end:"18:00"}]},{id:"w4",name:"Drew",preferredZone:"SIDE",leadWeight:4,availability:[{start:"16:00",end:"23:00"}]},{id:"w5",name:"Eden",preferredZone:"",leadWeight:6,availability:[]}],shows:[{id:"s1",name:"Main Stage",theater:"default",guests:8,showtimes:[{id:"main-open",room:1,start:"14:00",duration:60},{id:"main-eve",room:2,start:"18:00",duration:90}]},{id:"s2",name:"Side Room",theater:"default",guests:7,showtimes:[{id:"side-open",room:5,start:"14:00",duration:60},{id:"side-eve",room:6,start:"17:30",duration:60}]},{id:"s3",name:"Gallery",theater:"default",guests:22,showtimes:[{id:"gallery-eve",room:3,start:"19:00",duration:60}]}]}}
